version: '3.5'
services:
    php-nginx:
        container_name: php-nginx
        build:
            context: ./
            dockerfile: docker/php-nginx/.Dockerfile
        ports:
            - '80:80'
        networks:
            - laravel
        volumes:
            - ./:/var/www/html

    mariadb:
        image: mariadb:10.6
        container_name: maria_db
        command:
            --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        networks:
            - laravel
        volumes:
            - maria_db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}

networks:
    laravel:

volumes:
    maria_db_data:
